### PR TITLE
default image shown on item

### PR DESCRIPTION
**Pull request by mayurnemade7**
# Description

Placed a default image when user not provided image.
Screenshot 2022-07-14 at 8 42 50 PM

image

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @mayurnemade7, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by mayurnemade7** [comment]
Any help in solving this lint error

**Comment by mayurnemade7** [comment]
> Make sure all checks pass, only then you can merge the PR.

Even though I format with preetier lint error is not gone

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @mayurnemade7! You're now able to merge the PR.

**Pull request merged**
